### ISSUE TITLE
开启WEBDAV后Caddy无法启动

### ISSUE THREAD

**Issue by maple185** [jiix/WCMP#1]
WIN10下开启WEBDAV后Caddy无法启动，不开启没问题

**Comment by jiix** [comment]
无法复现，请把你的配置文件贴上来。

**Comment by maple185** [comment]
![Snipaste_2020-12-16_03-41-46](https://user-images.githubusercontent.com/54958410/102264522-afb60b00-3f0d-11eb-8243-d8eb38d90f11.png)
`# this is caddy global settings.
{
	experimental_http3
	email your@email.com
	admin off
}

##########################################################################################

# change this ":80" to "www.yourdomain.com"
# when your site are ready to go public.
# this :80 is only here for your local test.

:8100 {

    # change "site01" your site path
    root *  ..\www\site01
    
    #You should keep these standard things, unless you know what you are doing.
    php_fastcgi localhost:9000
    encode zstd gzip 
    file_server
    header -Server
}

:8101 {

    # change "site01" your site path
    root *  ..\www\site02
    
    #You should keep these standard things, unless you know what you are doing.
    php_fastcgi localhost:9000
    encode zstd gzip 
    file_server
    header -Server
}

:8111 {
  route /webdav/* {
    webdav {
      prefix /webdav/
      root *  ..\www\webdav
    }
  }
  basicauth /webdav/* {
	jiih JDJhJDEwJHY1SUpDYTZram9vMWhlTU1NNGZWVk9sTXlzV3hYYmdMWnA5Ry5mbkZvOVlEUzFBU2RERzUy
}
##########################################################################################

`

**Comment by maple185** [comment]
WIN

> 无法复现，请把你的配置文件贴上来。

WIN10 企业版 LTSC

**Comment by jiix** [comment]
换成这段试试
```
:8111 {
root *  ..\www\webdav

route {
	rewrite /webdav /webdav/
	webdav /webdav/* {
		prefix /webdav
	}
	file_server
}
    basicauth /webdav/* {
	jiih JDJhJDEwJHY1SUpDYTZram9vMWhlTU1NNGZWVk9sTXlzV3hYYmdMWnA5Ry5mbkZvOVlEUzFBU2RERzUy
}
```

**Comment by maple185** [comment]
> 换成这段试试
> 
> ```
> :8111 {
> root *  ..\www\webdav
> 
> route {
> 	rewrite /webdav /webdav/
> 	webdav /webdav/* {
> 		prefix /webdav
> 	}
> 	file_server
> }
>     basicauth /webdav/* {
> 	jiih JDJhJDEwJHY1SUpDYTZram9vMWhlTU1NNGZWVk9sTXlzV3hYYmdMWnA5Ry5mbkZvOVlEUzFBU2RERzUy
> }
> ```

换成这段以后解决了。感谢
