### ISSUE TITLE
没有MYSQL服务

### ISSUE THREAD

**Issue by maple185** [jiix/WCMP#2]
![Snipaste_2021-01-06_12-48-11](https://user-images.githubusercontent.com/54958410/103730512-018a1680-501e-11eb-8241-54dd0ac08927.png)
![Snipaste_2021-01-06_12-58-31](https://user-images.githubusercontent.com/54958410/103731121-62661e80-501f-11eb-8833-1a91c0063175.png)
面板MYSQL显示启动,但服务里并没有MYSQL项目.输入mysql -u root mysql报错`'mysql' 不是内部或外部命令，也不是可运行的程序或批处理文件。`文件指向`socket = /tmp/mysql.sock`但,并没有TMP文件夹

**Comment by maple185** [comment]
![Uploading Snipaste_2021-01-06_12-58-31.png…]()

**Comment by jiix** [comment]
试试先`cd E:\WCMP\mysql\bin`打开MySQL目录再运行`mysql -u root mysql`。

**Comment by jiix** [comment]
另外MySQL只是作为进程运行，而非服务。你可以在任务管理器—进程中找到**mysqld.exe**。
